## YAML Template.
---
spring:
  jpa:
    database: mysql
    show-sql: true 
    generate-ddl: true
    hibernate: 
      ddl-auto: create  


multitenancy: 
  apps: 
    dataSources: 
      -
        tenantId: panthera 
        url: jdbc:mysql://localhost:3306/panthera?useSSL=false 
        username: root
        password: admin
        driverClassName: com.mysql.jdbc.Driver 
      -
        tenantId: tiger
        url: jdbc:mysql://localhost:3306/tiger?useSSL=false
        username: root
        password: admin
        driverClassName: com.mysql.jdbc.Driver     
        
        
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org:
      hibernate:
        type: trace
        
        
        
        
        
        
        
        